'use strict';
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const publicDir = fs.existsSync(path.join(root, 'dist', 'index.html')) ? path.join(root, 'dist') : root;
const { mergeVisits, groupNearby, nearestLongitude, visitBounds, normalizeDate, formatDate } = require(path.join(publicDir, 'map-utils.js'));
const context = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(publicDir, 'data', 'places.js'), 'utf8'), context);
const data = JSON.parse(JSON.stringify(context.window.WORLD_MAP_DATA));
const places = mergeVisits(data);
console.log(`${data.blue.length} blue entries + ${data.red.length} red entries + ${(data.together || []).length} together entries; ${places.length} distinct places, ${places.filter(p => p.color === 'shared').length} shared.`);
const sample = { places: { p: { name: 'Test', type: 'city', coordinates: [14, 50] } }, blue: [{ place: 'p', date: '2024-02-29' }, { place: 'p', date: '2024-02-29' }], red: [{ place: 'p', date: '2025-03-01' }] };
const merged = mergeVisits(sample);
assert.equal(merged.length, 1);
assert.equal(merged[0].color, 'shared');
assert.deepEqual(merged[0].blue, ['2024-02-29']);
assert.deepEqual(merged[0].red, ['2025-03-01']);
assert.throws(() => mergeVisits({ ...sample, red: [{ place: 'missing', date: '2025-03-01' }] }), /Unknown place/);
assert.throws(() => mergeVisits({ ...sample, red: [{ place: 'p', date: '2025-02-29' }] }), /Invalid date/);
assert.equal(mergeVisits({ places: {}, blue: [], red: [] }).length, 0);
assert.deepEqual(groupNearby([{ x: 0, y: 0 }, { x: 20, y: 10 }, { x: 200, y: 100 }]).map(g => g.length), [2, 1]);
assert.equal(nearestLongitude(-179, 179), 181);
assert.equal(nearestLongitude(179, -179), -181);
assert.equal(formatDate(normalizeDate('2025')), '2025');
assert.equal(formatDate(normalizeDate('2023-11')), 'Nov 2023');
assert.equal(formatDate(normalizeDate({from:'2026-01',to:'2026-03'})), 'Jan–Mar 2026');
assert.equal(formatDate(normalizeDate({oneOf:['2018','2019']})), '2018 or 2019');
assert.equal(formatDate(normalizeDate(null)), 'Date not specified');
assert.throws(() => normalizeDate('2026-13'), /Invalid date/);
assert.throws(() => normalizeDate({from:'2026-03',to:'2026-01'}), /starts after/);
const shared = mergeVisits({places:sample.places,blue:[{place:'p',date:null}],red:[],together:[{place:'p',date:'2026'}]});
assert.equal(shared[0].color, 'shared');
assert.deepEqual(shared[0].blue, ['2026']);
assert.deepEqual(shared[0].red, ['2026']);
const crossing = visitBounds([[179, 20], [-179, 22]], 180);
assert.equal(crossing[1][0]-crossing[0][0], 2);
assert.deepEqual(visitBounds([],0), null);
assert.deepEqual(visitBounds([[14,50]],0), [[14,50],[14,50]]);
console.log('Date precision, shared visits, duplicates, date-line bounds and nearby grouping checks passed.');
